# Generated by Django 4.1.3 on 2023-04-22 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Limbus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='issue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
