# Generated by Django 4.1.3 on 2023-04-22 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Limbus', '0002_alter_bookissue_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Limbus.books')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Limbus.members')),
            ],
            options={
                'unique_together': {('member', 'book')},
            },
        ),
        migrations.CreateModel(
            name='ReturnedBooks',
            fields=[
                ('issue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('returned', models.BooleanField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Limbus.books')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Limbus.members')),
            ],
        ),
        migrations.DeleteModel(
            name='BookIssue',
        ),
    ]
