# Generated by Django 4.1.3 on 2023-04-22 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Limbus', '0003_issuedbooks_returnedbooks_delete_bookissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnedbooks',
            name='returned',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
