# Generated by Django 4.1.3 on 2023-04-28 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Limbus', '0005_rename_auth_id_bookauth_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauth',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Limbus.authors'),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Limbus.books'),
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Limbus.members'),
        ),
        migrations.AlterField(
            model_name='returnedbooks',
            name='book',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='returnedbooks',
            name='member',
            field=models.CharField(max_length=50),
        ),
    ]
