# Generated by Django 4.1.3 on 2023-05-16 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Limbus', '0006_alter_bookauth_auth_alter_issuedbooks_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubName', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='returnedbooks',
            name='book_isbn',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnedbooks',
            name='member_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issuedbooks',
            name='issue_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='members',
            name='memb_since',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returnedbooks',
            name='issue_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='returnedbooks',
            name='returned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='books',
            name='pubName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Limbus.publishers'),
        ),
    ]
