# Generated by Django 4.1.3 on 2023-06-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Limbus', '0008_alter_members_email_alter_members_phone_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='pubName',
            new_name='publisher',
        ),
    ]
